var resourcs = {
    VI: {
        errorMsg: "Có lỗi xảy ra vui lòng liên hệ Misa! ",
        titlePage: " bản ghi trên 1 trang",
        fileNameExport: "Danh_sach_nhan_vien",
        deleteMulti: "Bạn thực sự có muốn xóa những nhân viên đã chọn không?",
        confirmEdit: "Dữ liệu đã bị thay đổi bạn có muốn cất không?",
        errorEmployeeCode: "Mã nhân viên không đúng định dạng!",
        notNullFullName: "Tên không được phép để trống!",
        notNullEmployeeCode: "Mã không được phép để trống!",
        notNullDepartmentName: "Đơn vị không được phép để trống!",
        inputSearch: "Nhập từ khóa tìm kiếm",
    }
}
var misaEnum = {
    gender: {
        Male: "1",
        Female: "0",
        Other: "2"
    },
    genderNumber: {
        Male: {
            Value: 1,
            Text: "Nam"
        },
        Female: {
            Value: 0,
            Text: "Nữ"
        },
        Other: {
            Value: 2,
            Text: "Khác"
        }
    },
    editMode: {
        NoAction: 0, //Không thực hiện gì cả
        Add: 1, //Thực hiện thêm mới
        Edit: 2, //Thực hiện sửa
        View: 3 //Thực hiện xem
    },
    actionDelete: {
        NoAction: 0, //Không xóa
        One: 1, //Xóa một 
        Multi: 2, //Xóa nhiều
    }
}
var data = {
    listPageSize: [
        "10", "20", "30", "50", "100"
    ],
    listFieldAccountObject: [{
            name: "AccountObjectCode",
            text: "MÃ NHÀ CUNG CẤP",
            width: "130",
        },
        {
            name: "AccountObjectName",
            text: "TÊN NHÀ CUNG CẤP",
            width: "180",
        },
        {
            name: "Address",
            text: "ĐỊA CHỈ",
            width: "120",
        },
        {
            name: "TaxCode",
            text: "MÃ SỐ THUẾ",
            width: "100",
        },
        {
            name: "Phone",
            text: "SỐ ĐIỆN THOẠI",
            width: "115",
        },
        {
            name: "Website",
            text: "WEBSITE",
            width: "200",
            title: "Tên trang web công ty"
        },
        {
            name: "CreatedDate",
            text: "NGÀY TẠO",
            width: "115",
            type: "date"

        },
        {
            name: "MaximizeDebtAmount",
            text: "NỢ TỐI ĐA",
            width: '80',
            type: 'number'
        }

    ],
    listTabIndex: [
        "Liên hệ", "Điều khoản thanh toán", "Tài khoản ngân hàng", "Địa chỉ khác", "Ghi chú"
    ]
}
var dataTest = {
    listAccount: [{
            "AccountObjectId": "11452b0c-768e-5ff7-0d63-eeb1d8ed8cef",
            "AccountObjectCode": "NCC00004",
            "AccountObjectName": "Công ty MKUGN",
            "TaxCode": "143571",
            "Phone": "0336302541",
            "Website": "http://minh1331.vn",
            "AccountObjectGroupListId": null,
            "Address": "Thừa Thiên Huế",
            "EmployeeId": "4989ff24-23e7-7b82-b6d2-89b22d10517e",
            "Prefix": "Ông",
            "EinvoiceContactName": "Nguyễn Hồ Trang",
            "EinvoiceContactMobile": "0875946171",
            "EinvoiceContactEmail": "Anh778@gmail.com",
            "LegalRepresentative": "Nguyễn Văn Tuấn",
            "PaymentTermId": "60b82625-3612-24de-9617-6d44a4db1359",
            "MaximizeDebtAmount": 20,
            "DueTime": 11,
            "AccountObjectBankAccount": null,
            "AccountObjectShippingAddress": null,
            "Country": "Việt Nam",
            "District": null,
            "WardOrCommune": null,
            "ProvinceOrCity": "Thừa Thiên Huế",
            "Description": "",
            "PayAccountId": "548dce5f-5f29-4617-725d-e2ec561b0f41",
            "CreatedDate": "2007-05-21T20:18:55",
            "CreatedBy": "Adolph Francisco",
            "ModifiedDate": "11/08/1986 03:05:24",
            "ModifiedBy": "Jason Blackmon"
        },
        {
            "AccountObjectId": "1152da18-24d8-65b6-0380-e8e2a817c80e",
            "AccountObjectCode": "NCC00049",
            "AccountObjectName": "Công ty KJHUM",
            "TaxCode": "107547",
            "Phone": "0329500933",
            "Website": "http://minh1692.edu",
            "AccountObjectGroupListId": null,
            "Address": "Nam Định",
            "EmployeeId": "6a763a51-4322-5c5a-b5d2-89b22d10517e",
            "Prefix": "Ông",
            "EinvoiceContactName": "Trần Thế Huy",
            "EinvoiceContactMobile": "0334551308",
            "EinvoiceContactEmail": "Tuy206@gmail.com",
            "LegalRepresentative": "Đỗ Thị Phương",
            "PaymentTermId": "359963d8-1e69-5220-7ecc-ee92bf437a3f",
            "MaximizeDebtAmount": 50,
            "DueTime": 14,
            "AccountObjectBankAccount": null,
            "AccountObjectShippingAddress": null,
            "Country": "Việt Nam",
            "District": null,
            "WardOrCommune": null,
            "ProvinceOrCity": "Nam Định",
            "Description": "",
            "PayAccountId": "5bd71cda-209f-2ade-54d1-35c781481818",
            "CreatedDate": "2005-09-21T09:43:48",
            "CreatedBy": "Shonda Leake",
            "ModifiedDate": "01/01/1970 00:05:07",
            "ModifiedBy": "Marylin Bankston"
        },
        {
            "AccountObjectId": "11f7089b-33e6-371a-f817-7000f455f3d5",
            "AccountObjectCode": "NCC00021",
            "AccountObjectName": "Công ty DRNAL",
            "TaxCode": "183315",
            "Phone": "0347351171",
            "Website": "http://ngoc3282.com",
            "AccountObjectGroupListId": null,
            "Address": "Long An",
            "EmployeeId": "1f85f165-3ed3-370a-b7d2-89b22d10517e",
            "Prefix": "Bà",
            "EinvoiceContactName": "Nguyễn Thế Hoàng",
            "EinvoiceContactMobile": "0817926108",
            "EinvoiceContactEmail": "Song22945@gmail.com",
            "LegalRepresentative": "Phạm Văn Hoàng",
            "PaymentTermId": "49b5613c-112f-5d16-636f-d59c8dd9bef2",
            "MaximizeDebtAmount": 17,
            "DueTime": 80,
            "AccountObjectBankAccount": null,
            "AccountObjectShippingAddress": null,
            "Country": "Việt Nam",
            "District": null,
            "WardOrCommune": null,
            "ProvinceOrCity": "Long An",
            "Description": "",
            "PayAccountId": "5bd71cda-209f-2ade-54d1-35c781481818",
            "CreatedDate": "1973-12-04T23:45:59",
            "CreatedBy": "Delcie Abney",
            "ModifiedDate": "01/01/1970 02:09:09",
            "ModifiedBy": "Corinna Bratton"
        },
        {
            "AccountObjectId": "142cb08f-7c31-21fa-8e90-67245e8b283e",
            "AccountObjectCode": "NCC00000",
            "AccountObjectName": "Công ty MVOXN",
            "TaxCode": "155986",
            "Phone": "0395601922",
            "Website": "http://ngoc5955.com",
            "AccountObjectGroupListId": null,
            "Address": "An Giang",
            "EmployeeId": "1e5e96fa-5d7a-599d-27c2-579daad24557",
            "Prefix": "Ông",
            "EinvoiceContactName": "Vũ Văn Anh",
            "EinvoiceContactMobile": "0331755304",
            "EinvoiceContactEmail": "Vanh04612@gmail.com",
            "LegalRepresentative": "Nguyễn Tiến Huy",
            "PaymentTermId": "2181e1b4-3cf9-2495-bbec-c0283040ad25",
            "MaximizeDebtAmount": 88,
            "DueTime": 79,
            "AccountObjectBankAccount": null,
            "AccountObjectShippingAddress": null,
            "Country": "Việt Nam",
            "District": null,
            "WardOrCommune": null,
            "ProvinceOrCity": "An Giang",
            "Description": "",
            "PayAccountId": "548dce5f-5f29-4617-725d-e2ec561b0f41",
            "CreatedDate": "1970-01-01T00:07:13",
            "CreatedBy": "Letha Bolt",
            "ModifiedDate": "01/01/1970 00:00:04",
            "ModifiedBy": "Abraham Acevedo"
        },
        {
            "AccountObjectId": "14c0ce35-1687-459c-1acb-66948daf6128",
            "AccountObjectCode": "NCC00032",
            "AccountObjectName": "Công ty KQAZJ",
            "TaxCode": "170684",
            "Phone": "0843377579",
            "Website": "http://lan4697.vn",
            "AccountObjectGroupListId": null,
            "Address": "Hòa Bình",
            "EmployeeId": "62af2231-78a7-7caa-cd1d-086412a8ea97",
            "Prefix": "Bà",
            "EinvoiceContactName": "Vũ Thị Phương",
            "EinvoiceContactMobile": "0341846922",
            "EinvoiceContactEmail": "Lam51039@gmail.com",
            "LegalRepresentative": "Vũ Bảo Bảo",
            "PaymentTermId": "2181e1b4-3cf9-2495-bbec-c0283040ad25",
            "MaximizeDebtAmount": 94,
            "DueTime": 31,
            "AccountObjectBankAccount": null,
            "AccountObjectShippingAddress": null,
            "Country": "Việt Nam",
            "District": null,
            "WardOrCommune": null,
            "ProvinceOrCity": "Hòa Bình",
            "Description": "",
            "PayAccountId": "589edf01-198a-4ff5-958e-fb52fd75a1d4",
            "CreatedDate": "1970-01-01T00:01:38",
            "CreatedBy": "Melia Gates",
            "ModifiedDate": "04/16/2009 01:11:50",
            "ModifiedBy": "Dong Alarcon"
        },
        {
            "AccountObjectId": "17120d02-6ab5-3e43-18cb-66948daf6128",
            "AccountObjectCode": "NCC00003",
            "AccountObjectName": "Công ty IUMMC",
            "TaxCode": "127623",
            "Phone": "0885979808",
            "Website": "http://lan3337.edu",
            "AccountObjectGroupListId": null,
            "Address": "Ninh Bình",
            "EmployeeId": "409dcd1a-426a-23f7-3a35-0028ed526dd0",
            "Prefix": "Ông",
            "EinvoiceContactName": "Vũ Phương Nhung",
            "EinvoiceContactMobile": "0937357757",
            "EinvoiceContactEmail": "Nga798@gmail.com",
            "LegalRepresentative": "Lý Thảo Anh",
            "PaymentTermId": "359963d8-1e69-5220-7ecc-ee92bf437a3f",
            "MaximizeDebtAmount": 56,
            "DueTime": 20,
            "AccountObjectBankAccount": null,
            "AccountObjectShippingAddress": null,
            "Country": "Việt Nam",
            "District": null,
            "WardOrCommune": null,
            "ProvinceOrCity": "Ninh Bình",
            "Description": "",
            "PayAccountId": "589edf01-198a-4ff5-958e-fb52fd75a1d4",
            "CreatedDate": "1999-03-08T13:32:34",
            "CreatedBy": "Miyoko Mckinney",
            "ModifiedDate": "03/12/2018 12:55:48",
            "ModifiedBy": "Hong Beaudoin"
        },
        {
            "AccountObjectId": "179d5bc0-2405-67f7-9590-67245e8b283e",
            "AccountObjectCode": "NCC00052",
            "AccountObjectName": "Công ty YOSET",
            "TaxCode": "128850",
            "Phone": "0318948993",
            "Website": "http://ngoc5358.vn",
            "AccountObjectGroupListId": null,
            "Address": "Phú Thọ",
            "EmployeeId": "407db4d1-222b-287d-0135-60b3ebf808a9",
            "Prefix": "Bà",
            "EinvoiceContactName": "Nguyễn Đình Nam",
            "EinvoiceContactMobile": "0319299327",
            "EinvoiceContactEmail": "Ly166@gmail.com",
            "LegalRepresentative": "Trần Ngọc Hoàng",
            "PaymentTermId": "359963d8-1e69-5220-7ecc-ee92bf437a3f",
            "MaximizeDebtAmount": 29,
            "DueTime": 29,
            "AccountObjectBankAccount": null,
            "AccountObjectShippingAddress": null,
            "Country": "Việt Nam",
            "District": null,
            "WardOrCommune": null,
            "ProvinceOrCity": "Phú Thọ",
            "Description": "",
            "PayAccountId": "68daa090-552d-1bc6-e8e4-8adc5263917a",
            "CreatedDate": "2017-11-23T22:08:26",
            "CreatedBy": "Alphonso Meeks",
            "ModifiedDate": "04/24/1984 17:16:19",
            "ModifiedBy": "Dimple Alba"
        },
        {
            "AccountObjectId": "1b336f56-7ee3-7ceb-1ccb-66948daf6128",
            "AccountObjectCode": "NCC00056",
            "AccountObjectName": "Công ty JJEND",
            "TaxCode": "154668",
            "Phone": "0371170316",
            "Website": "http://ngoc7384.com",
            "AccountObjectGroupListId": null,
            "Address": "Vĩnh Long",
            "EmployeeId": "5de704c2-573f-1a71-1a80-de64d090a2c2",
            "Prefix": "Bà",
            "EinvoiceContactName": "Lý Phương Linh",
            "EinvoiceContactMobile": "0390313338",
            "EinvoiceContactEmail": "Van6529@misa.com",
            "LegalRepresentative": "Phan Phan Hoàng",
            "PaymentTermId": "26a546dc-51ef-474e-ec75-f433c80be791",
            "MaximizeDebtAmount": 33,
            "DueTime": 15,
            "AccountObjectBankAccount": null,
            "AccountObjectShippingAddress": null,
            "Country": "Việt Nam",
            "District": null,
            "WardOrCommune": null,
            "ProvinceOrCity": "Vĩnh Long",
            "Description": "",
            "PayAccountId": "30d41e52-5e66-72bc-6c1c-b47866e0b131",
            "CreatedDate": "1970-01-01T00:04:31",
            "CreatedBy": "Alejandro Espinal",
            "ModifiedDate": "01/01/1970 00:00:18",
            "ModifiedBy": "Glory Hammond"
        },
        {
            "AccountObjectId": "1ded3dd7-32db-5bc9-9190-67245e8b283e",
            "AccountObjectCode": "NCC00019",
            "AccountObjectName": "Công ty YWSKM",
            "TaxCode": "157693",
            "Phone": "0974266355",
            "Website": "http://tri2836.vn",
            "AccountObjectGroupListId": null,
            "Address": "Tuyên Quang",
            "EmployeeId": "197fda97-5a35-781d-0e77-d9ebc53aac3d",
            "Prefix": "Bà",
            "EinvoiceContactName": "Vũ Thảo Trang",
            "EinvoiceContactMobile": "0985565339",
            "EinvoiceContactEmail": "Trinh9890@gmail.com",
            "LegalRepresentative": "Phạm Thị Yến",
            "PaymentTermId": "26a546dc-51ef-474e-ec75-f433c80be791",
            "MaximizeDebtAmount": 85,
            "DueTime": 13,
            "AccountObjectBankAccount": null,
            "AccountObjectShippingAddress": null,
            "Country": "Việt Nam",
            "District": null,
            "WardOrCommune": null,
            "ProvinceOrCity": "Tuyên Quang",
            "Description": "",
            "PayAccountId": "589edf01-198a-4ff5-958e-fb52fd75a1d4",
            "CreatedDate": "1997-03-20T09:03:51",
            "CreatedBy": "Winnifred Brantley",
            "ModifiedDate": "11/15/2000 19:41:57",
            "ModifiedBy": "Grant Ackerman"
        },
    ]
}

export {
    resourcs,
    misaEnum,
    data,
    dataTest
};