//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Fresher.Web12.Core.Resourcs.EntitiesVN {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountObjectVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountObjectVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Fresher.Web12.Core.Resourcs.EntitiesVN.AccountObjectVN", typeof(AccountObjectVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp.
        /// </summary>
        public static string AccountObjectCode {
            get {
                return ResourceManager.GetString("AccountObjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhà cung cấp.
        /// </summary>
        public static string AccountObjectName {
            get {
                return ResourceManager.GetString("AccountObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đất nước.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ghi chú.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quận/Huyện.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số ngày được nợ.
        /// </summary>
        public static string DueTime {
            get {
                return ResourceManager.GetString("DueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email người liên hệ.
        /// </summary>
        public static string EinvoiceContactEmail {
            get {
                return ResourceManager.GetString("EinvoiceContactEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại người liên hệ.
        /// </summary>
        public static string EinvoiceContactMobile {
            get {
                return ResourceManager.GetString("EinvoiceContactMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Họ và tên người liên hệ.
        /// </summary>
        public static string EinvoiceContactName {
            get {
                return ResourceManager.GetString("EinvoiceContactName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên.
        /// </summary>
        public static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đại diện theo pháp luật.
        /// </summary>
        public static string LegalRepresentative {
            get {
                return ResourceManager.GetString("LegalRepresentative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nợ tối đa.
        /// </summary>
        public static string MaximizeDebtAmount {
            get {
                return ResourceManager.GetString("MaximizeDebtAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài khoản công nợ.
        /// </summary>
        public static string PayAccountCode {
            get {
                return ResourceManager.GetString("PayAccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài khoản công nợ.
        /// </summary>
        public static string PayAccountName {
            get {
                return ResourceManager.GetString("PayAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã điều khoản.
        /// </summary>
        public static string PaymentTermCode {
            get {
                return ResourceManager.GetString("PaymentTermCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên điều khoản.
        /// </summary>
        public static string PaymentTermName {
            get {
                return ResourceManager.GetString("PaymentTermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xưng hô.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thành phố.
        /// </summary>
        public static string ProvinceOrCity {
            get {
                return ResourceManager.GetString("ProvinceOrCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^NCC[0-9]{5}$.
        /// </summary>
        public static string RegexAccountObjectCode {
            get {
                return ResourceManager.GetString("RegexAccountObjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế.
        /// </summary>
        public static string TaxCode {
            get {
                return ResourceManager.GetString("TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DANH SÁCH NHÀ CUNG CẤP.
        /// </summary>
        public static string TitleExcelExport {
            get {
                return ResourceManager.GetString("TitleExcelExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phường/Xã.
        /// </summary>
        public static string WardOrCommune {
            get {
                return ResourceManager.GetString("WardOrCommune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
    }
}
